TYPE "UDT_RouteFsmWork"
{ S7_Optimized_Access := 'TRUE' }
STRUCT
  lastCmd    : USINT;
  startEdge  : BOOL;
  stopOpEdge : BOOL;

  stepCnt    : INT;
  stepIdx    : INT;
  i          : INT;
  slot       : UINT;

  anyFault   : BOOL;
  anyLocal   : BOOL;
  allStopped : BOOL;
  stepOk     : BOOL;

  lockOkAll  : BOOL;
  lockOkOne  : BOOL;

  cmdOk      : BOOL;
  dummyOk    : BOOL;    //  Для анонімних викликів

  safetyHit  : BOOL;
END_STRUCT
END_TYPE
